import E_PlayerPosition from "../../type/enums/e_player_position.js";
import E_PlayerSkill from "../../type/enums/e_player_skill.js";
import T_TrainingPlans from "../../type/t_training_plans.js";

const TRAINING_PLANS: T_TrainingPlans = {
    [E_PlayerPosition.GoalKeeper]: [
        E_PlayerSkill.penalty_area_safety,
        E_PlayerSkill.catch_safety,
        E_PlayerSkill.fitness,
        E_PlayerSkill.speed,
        E_PlayerSkill.duell,
        E_PlayerSkill.endurance,
        E_PlayerSkill.shot,
        E_PlayerSkill.two_footed,
    ],
    [E_PlayerPosition.CentreBack]: [
        E_PlayerSkill.pass,
        E_PlayerSkill.duell,
        E_PlayerSkill.fitness,
        E_PlayerSkill.cover,
        E_PlayerSkill.speed,
        E_PlayerSkill.endurance,
        E_PlayerSkill.header,
        E_PlayerSkill.shot,
        E_PlayerSkill.running,
        E_PlayerSkill.two_footed,
    ],
    [E_PlayerPosition.Wingback]: [
        E_PlayerSkill.pass,
        E_PlayerSkill.duell,
        E_PlayerSkill.fitness,
        E_PlayerSkill.cover,
        E_PlayerSkill.speed,
        E_PlayerSkill.endurance,
        E_PlayerSkill.header,
        E_PlayerSkill.shot,
        E_PlayerSkill.running,
        E_PlayerSkill.two_footed,
    ],
    [E_PlayerPosition.DefensiveMidfielder]: [
        E_PlayerSkill.duell,
        E_PlayerSkill.pass,
        E_PlayerSkill.fitness,
        E_PlayerSkill.cover,
        E_PlayerSkill.endurance,
        E_PlayerSkill.speed,
        E_PlayerSkill.shot,
        E_PlayerSkill.running,
        E_PlayerSkill.header,
        E_PlayerSkill.two_footed,
    ],
    [E_PlayerPosition.LeftMidfielder]: [
        E_PlayerSkill.endurance,
        E_PlayerSkill.fitness,
        E_PlayerSkill.speed,
        E_PlayerSkill.header,
        E_PlayerSkill.pass,
        E_PlayerSkill.running,
        E_PlayerSkill.duell,
        E_PlayerSkill.shot,
        E_PlayerSkill.cover,
        E_PlayerSkill.two_footed,
    ],
    [E_PlayerPosition.RightMidfielder]: [
        E_PlayerSkill.endurance,
        E_PlayerSkill.fitness,
        E_PlayerSkill.speed,
        E_PlayerSkill.header,
        E_PlayerSkill.pass,
        E_PlayerSkill.running,
        E_PlayerSkill.duell,
        E_PlayerSkill.shot,
        E_PlayerSkill.cover,
        E_PlayerSkill.two_footed,
    ],
    [E_PlayerPosition.AttackingMidfielder]: [
        E_PlayerSkill.running,
        E_PlayerSkill.fitness,
        E_PlayerSkill.speed,
        E_PlayerSkill.endurance,
        E_PlayerSkill.two_footed,
        E_PlayerSkill.shot,
        E_PlayerSkill.duell,
        E_PlayerSkill.pass,
        E_PlayerSkill.header,
        E_PlayerSkill.cover,
    ],
    [E_PlayerPosition.Striker]: [
        E_PlayerSkill.running,
        E_PlayerSkill.fitness,
        E_PlayerSkill.speed,
        E_PlayerSkill.two_footed,
        E_PlayerSkill.endurance,
        E_PlayerSkill.duell,
        E_PlayerSkill.shot,
        E_PlayerSkill.header,
        E_PlayerSkill.pass,
        E_PlayerSkill.cover,
    ],
};

export default TRAINING_PLANS;